### ISSUE TITLE
[Suggestion] Mark positions with cursor

### ISSUE THREAD

**Issue by TheTimmaeh** [kankaristo/atom-multi-cursor-plus#16]
Hey, would it be possible to mark new positions via mouse?

e.g. I would start at the first position with Alt+X and then hold Alt and mark the other positions by clicking with the cursor.

This would make things easier and not eat up so many key bindings.

Is this even possible?

**Comment by kankaristo** [comment]
Atom has this built-in, it's `ctrl-shift-click`. Not sure if it's possible to change the keybinding.
