### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by johngeorgewright** [kankaristo/atom-multi-cursor-plus#2]
Since opening up Atom today this package hasn't worked. I'm not getting errors; the functionality just stopped working :(

Atom 1.0.3 - Mac
multi-cursor-plus 0.1.3

![multimark](https://cloud.githubusercontent.com/assets/1423566/9082439/eb735f46-3b5b-11e5-965f-c0c8d0679e39.gif)

**Comment by kankaristo** [comment]
Thanks for reporting this, I just noticed it's broken on Linux too.

Atom has probably changed the way that multiple cursors are joined when they touch each other. Atom doesn't seem to like having two cursors at the same position, which is essentially all that marking does.

The current implementation is pretty hackish, so I'm not surprised it broke. I'll take a look at this when I find the time, but pull requests are welcome too!

**Comment by JulianNorton** [comment]
works for me on OSX with cmd clicking.

**Comment by kankaristo** [comment]
This should be fixed now, I'll publish a new version soon.
