### ISSUE TITLE
Can't move to left/right

### ISSUE THREAD

**Issue by alexandernst** [kankaristo/atom-multi-cursor-plus#8]
I'm using the default keymaps and moving up/down (while holding Alt) works fine, but moving left/right will move all of the cursors instead of the "main" cursor.

Latest stable Atom on OS X

**Comment by kankaristo** [comment]
I think Atom added some new text movement keybindings a while ago. I'll probably have to update the README with a note about that.

Could you take a look at what package/command is capturing the keybinding? Open the keybinding resolver (command palette: "Key Binding Resolver: Toggle") and press `Alt-left` and `Alt-right`. Some other command is probably using the same keybinding.

**Comment by alexandernst** [comment]
I did what you asked. The commands are handled by `atom-text-editor`. The two commands are:

* `editor:move-to-beginning-of-word`
* `editor:move-to-end-of-word`

**Comment by kankaristo** [comment]
Try putting these in your keymap.cson:
```cson
'atom-workspace atom-text-editor':
    # Unset core editor keybindings (conflict with multi-cursor-plus)
    'alt-left': 'unset!'
    'alt-right': 'unset!'
```

You have to put them before the keybindings for multi-cursor-plus. If this fixes the keybindings, I'll add a note about it to README.md.

**Comment by alexandernst** [comment]
Yes, that works. Anyways, pretty much all the default keymaps in this plugin don't work. I guess it's because of the same reason.

**Comment by kankaristo** [comment]
I updated README.md with all the keybindings you need to unset in order for multi-cursor-plus to work correctly. Please re-open the issue and let me know if something is still not working correctly (I don't have an OS X machine to test these on).

Thanks for reporting this!
